linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable:
    - dupl
    - errcheck
    - errname
    - forbidigo
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosimple
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck

  disable:
    - govet
    - wsl

issues:
  exclude-rules:
    - linters:
        - gosimple
      text: "S1016"

run:
  issues-exit-code: 1
