version: '3'
services:
  crypto:
    build:
      context: ./crypto
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - rabbitmq_go_net

  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rabbitmq_go_net

  logger-consumer:
    restart: always
    build:
      context: ./logger-consumer
      dockerfile: Dockerfile
    networks:
      - rabbitmq_go_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
