// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	"github.com/vadimpk/gses-2023/core/internal/service"
)

// EmailAPI is an autogenerated mock type for the EmailAPI type
type EmailAPI struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, opts
func (_m *EmailAPI) Send(ctx context.Context, opts *service.SendOptions) error {
	ret := _m.Called(ctx, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.SendOptions) error); ok {
		r0 = rf(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEmailAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmailAPI creates a new instance of EmailAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmailAPI(t mockConstructorTestingTNewEmailAPI) *EmailAPI {
	mock := &EmailAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
