name: "Core Service Tests"

on:
  push:
    branches:
      - "**"

defaults:
  run:
    working-directory: core

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install go mods
        if: always()
        run: go mod download

      - name: "Run unit tests"
        if: always()
        run: go test -v ./...